
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bf108c1a643'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('event_date', sa.String(), nullable=True),
    sa.Column('participants', sa.Integer(), nullable=True),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('action_parameters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('param_type', sa.String(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_parameters_action_id'), 'action_parameters', ['action_id'], unique=False)
    op.create_table('action_proposals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('entity_name', sa.String(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('proposed_by', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('reasoning_conclusion', sa.Text(), nullable=True),
    sa.Column('reasoning_confidence', sa.Float(), nullable=True),
    sa.Column('reasoning_evidence', sa.Text(), nullable=True),
    sa.Column('reasoning_alternative_hypotheses', sa.Text(), nullable=True),
    sa.Column('reasoning_suggested_actions', sa.Text(), nullable=True),
    sa.Column('action_definition_id', sa.String(), nullable=True),
    sa.Column('action_definition_name', sa.String(), nullable=True),
    sa.Column('action_definition_description', sa.Text(), nullable=True),
    sa.Column('action_definition_requires_approval', sa.Boolean(), nullable=True),
    sa.Column('action_definition_preconditions', sa.Text(), nullable=True),
    sa.Column('action_definition_side_effects', sa.Text(), nullable=True),
    sa.Column('action_definition_write_back_targets', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_status',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('agent_type', sa.String(), nullable=False),
    sa.Column('agent_status', sa.String(), nullable=True),
    sa.Column('last_run', sa.DateTime(), nullable=True),
    sa.Column('total_memories', sa.Integer(), nullable=True),
    sa.Column('episodic_memories', sa.Integer(), nullable=True),
    sa.Column('semantic_memories', sa.Integer(), nullable=True),
    sa.Column('procedural_memories', sa.Integer(), nullable=True),
    sa.Column('total_experiences', sa.Integer(), nullable=True),
    sa.Column('knowledge_items', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('perception_ability', sa.Float(), nullable=True),
    sa.Column('reasoning_ability', sa.Float(), nullable=True),
    sa.Column('planning_ability', sa.Float(), nullable=True),
    sa.Column('learning_ability', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('entity_name', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('budget_amount', sa.Integer(), nullable=True),
    sa.Column('used_amount', sa.Integer(), nullable=True),
    sa.Column('remaining_amount', sa.Integer(), nullable=True),
    sa.Column('execution_rate', sa.Float(), nullable=True),
    sa.Column('budget_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('thread_id', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_thread_id'), 'chat_messages', ['thread_id'], unique=False)
    op.create_table('chat_threads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_threads_user_id'), 'chat_threads', ['user_id'], unique=False)
    op.create_table('clinical_trials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('trial_phase', sa.String(), nullable=True),
    sa.Column('enrolled_patients', sa.Integer(), nullable=True),
    sa.Column('follow_up_count', sa.Integer(), nullable=True),
    sa.Column('drug_usage', sa.Integer(), nullable=True),
    sa.Column('report_content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('risk_type', sa.String(), nullable=True),
    sa.Column('alert_description', sa.Text(), nullable=True),
    sa.Column('alert_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_name', sa.String(), nullable=True),
    sa.Column('rule_type', sa.String(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('rule_description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_drivers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('driver_type', sa.String(), nullable=True),
    sa.Column('driver_name', sa.String(), nullable=True),
    sa.Column('impact_factor', sa.Float(), nullable=True),
    sa.Column('related_expenses', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('prescription_potential', sa.Integer(), nullable=True),
    sa.Column('influence_level', sa.Integer(), nullable=True),
    sa.Column('cooperation_willingness', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_compliances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('meeting_frequency', sa.Integer(), nullable=True),
    sa.Column('real_name_verified', sa.Boolean(), nullable=True),
    sa.Column('compliance_history', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('department_researches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('department_id', sa.String(), nullable=True),
    sa.Column('bed_count', sa.Integer(), nullable=True),
    sa.Column('outpatient_volume', sa.Integer(), nullable=True),
    sa.Column('competitor_share', sa.Float(), nullable=True),
    sa.Column('our_share', sa.Float(), nullable=True),
    sa.Column('growth_potential', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doctors',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('specialty', sa.Text(), nullable=True),
    sa.Column('prescription_power', sa.Integer(), nullable=True),
    sa.Column('influence_score', sa.Integer(), nullable=True),
    sa.Column('prescription_volume', sa.Integer(), nullable=True),
    sa.Column('last_visit_date', sa.String(), nullable=True),
    sa.Column('next_recommended_visit_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense_classifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('expense_type', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('cost_center', sa.String(), nullable=True),
    sa.Column('approval_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense_compliances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('total_labor_fee', sa.Integer(), nullable=True),
    sa.Column('total_frequency', sa.Integer(), nullable=True),
    sa.Column('compliance_status', sa.String(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expense_rois',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('expense_amount', sa.Integer(), nullable=True),
    sa.Column('revenue_generated', sa.Integer(), nullable=True),
    sa.Column('roi_ratio', sa.Float(), nullable=True),
    sa.Column('attribution_model', sa.String(), nullable=True),
    sa.Column('calculation_period', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospital_developments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('development_stage', sa.String(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('resource_allocation', sa.Integer(), nullable=True),
    sa.Column('timeline', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospital_strategies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('strategy_type', sa.String(), nullable=True),
    sa.Column('sales_ratio', sa.Float(), nullable=True),
    sa.Column('vacancy_rate', sa.Float(), nullable=True),
    sa.Column('consumption_progress', sa.Float(), nullable=True),
    sa.Column('overlapping_hospitals', sa.Integer(), nullable=True),
    sa.Column('flow_direction', sa.String(), nullable=True),
    sa.Column('contract_ratio', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hospitals',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('level', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('beds', sa.Integer(), nullable=True),
    sa.Column('access_status', sa.String(), nullable=True),
    sa.Column('procurement_mode', sa.String(), nullable=True),
    sa.Column('annual_revenue', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inference_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=True),
    sa.Column('rule_name', sa.String(), nullable=True),
    sa.Column('result_type', sa.String(), nullable=True),
    sa.Column('source_entity_id', sa.String(), nullable=True),
    sa.Column('target_entity_id', sa.String(), nullable=True),
    sa.Column('inferred_link_type', sa.String(), nullable=True),
    sa.Column('inferred_property', sa.String(), nullable=True),
    sa.Column('inferred_value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inference_rules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('rule_type', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('ttl', sa.Integer(), nullable=True),
    sa.Column('auto_apply', sa.Boolean(), nullable=True),
    sa.Column('condition_pattern', sa.Text(), nullable=True),
    sa.Column('condition_filters', sa.Text(), nullable=True),
    sa.Column('condition_description', sa.Text(), nullable=True),
    sa.Column('conclusion_type', sa.String(), nullable=True),
    sa.Column('conclusion_source_pattern', sa.Text(), nullable=True),
    sa.Column('conclusion_target_pattern', sa.Text(), nullable=True),
    sa.Column('conclusion_link_type', sa.String(), nullable=True),
    sa.Column('conclusion_strength_formula', sa.Text(), nullable=True),
    sa.Column('conclusion_entity_pattern', sa.Text(), nullable=True),
    sa.Column('conclusion_property', sa.String(), nullable=True),
    sa.Column('conclusion_value_formula', sa.Text(), nullable=True),
    sa.Column('conclusion_alert_type', sa.String(), nullable=True),
    sa.Column('conclusion_alert_message_template', sa.Text(), nullable=True),
    sa.Column('conclusion_alert_severity', sa.String(), nullable=True),
    sa.Column('conclusion_tag_entity_pattern', sa.Text(), nullable=True),
    sa.Column('conclusion_tag', sa.String(), nullable=True),
    sa.Column('confidence_base', sa.Float(), nullable=True),
    sa.Column('confidence_modifiers', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('labor_payments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('payment_type', sa.String(), nullable=True),
    sa.Column('total_persons', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Integer(), nullable=True),
    sa.Column('payment_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_potentials',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('potential_value', sa.Integer(), nullable=True),
    sa.Column('penetration_rate', sa.Float(), nullable=True),
    sa.Column('market_share', sa.Float(), nullable=True),
    sa.Column('competitor_share', sa.Float(), nullable=True),
    sa.Column('growth_opportunity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meeting_compliances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('meeting_duration', sa.Float(), nullable=True),
    sa.Column('topic_alignment', sa.Float(), nullable=True),
    sa.Column('topic_repetition', sa.Float(), nullable=True),
    sa.Column('compliance_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('object_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('object_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=True),
    sa.Column('preconditions', sa.Text(), nullable=True),
    sa.Column('side_effects', sa.Text(), nullable=True),
    sa.Column('write_back_targets', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_object_actions_object_id'), 'object_actions', ['object_id'], unique=False)
    op.create_table('object_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('object_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('related_object_id', sa.String(), nullable=True),
    sa.Column('related_object_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_object_events_object_id'), 'object_events', ['object_id'], unique=False)
    op.create_table('object_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('link_type', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('target_name', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=False),
    sa.Column('link_strength', sa.Float(), nullable=True),
    sa.Column('link_frequency', sa.String(), nullable=True),
    sa.Column('link_volume', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_object_links_source_id'), 'object_links', ['source_id'], unique=False)
    op.create_table('ontology_objects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('object_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('lifecycle_stage', sa.String(), nullable=True),
    sa.Column('sentiment', sa.String(), nullable=True),
    sa.Column('compliance_risk_level', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patient_programs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('program_type', sa.String(), nullable=True),
    sa.Column('enrolled_patients', sa.Integer(), nullable=True),
    sa.Column('active_patients', sa.Integer(), nullable=True),
    sa.Column('drug_switch_count', sa.Integer(), nullable=True),
    sa.Column('commercial_insurance_count', sa.Integer(), nullable=True),
    sa.Column('reimbursement_amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pdca_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plan_type', sa.String(), nullable=True),
    sa.Column('plan_content', sa.Text(), nullable=True),
    sa.Column('do_actions', sa.Text(), nullable=True),
    sa.Column('check_results', sa.Text(), nullable=True),
    sa.Column('act_improvements', sa.Text(), nullable=True),
    sa.Column('cycle_status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_flows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=True),
    sa.Column('flow_direction', sa.String(), nullable=True),
    sa.Column('flow_volume', sa.Integer(), nullable=True),
    sa.Column('flow_value', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('sales', sa.Integer(), nullable=True),
    sa.Column('market_share', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recovery_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('doctor_name', sa.String(), nullable=True),
    sa.Column('risk_reason', sa.Text(), nullable=True),
    sa.Column('plan_status', sa.String(), nullable=True),
    sa.Column('validated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reminders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('reminder_type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminders_user_id'), 'reminders', ['user_id'], unique=False)
    op.create_table('research_collaborations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('collaboration_type', sa.String(), nullable=True),
    sa.Column('partner_institution', sa.String(), nullable=True),
    sa.Column('research_topic', sa.String(), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('start_date', sa.String(), nullable=True),
    sa.Column('end_date', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rws_projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('project_name', sa.String(), nullable=True),
    sa.Column('project_type', sa.String(), nullable=True),
    sa.Column('project_status', sa.String(), nullable=True),
    sa.Column('centers', sa.Integer(), nullable=True),
    sa.Column('enrolled_patients', sa.Integer(), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('timeline', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_flows',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('flow_type', sa.String(), nullable=True),
    sa.Column('target_value', sa.Integer(), nullable=True),
    sa.Column('actual_value', sa.Integer(), nullable=True),
    sa.Column('achievement_rate', sa.Float(), nullable=True),
    sa.Column('yoy_growth', sa.Float(), nullable=True),
    sa.Column('mom_growth', sa.Float(), nullable=True),
    sa.Column('dimension', sa.String(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_reps',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('performance', sa.Integer(), nullable=True),
    sa.Column('quota_achievement', sa.Integer(), nullable=True),
    sa.Column('ytd_sales', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_targets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('dimension', sa.String(), nullable=True),
    sa.Column('target_value', sa.Integer(), nullable=True),
    sa.Column('actual_value', sa.Integer(), nullable=True),
    sa.Column('forecast_value', sa.Integer(), nullable=True),
    sa.Column('achievement_rate', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scenario_parameters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('param_type', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('step_value', sa.Float(), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_parameters_scenario_id'), 'scenario_parameters', ['scenario_id'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('scenario_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('target_value', sa.Integer(), nullable=True),
    sa.Column('forecast_value', sa.Integer(), nullable=True),
    sa.Column('achievement_rate', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(), nullable=True),
    sa.Column('confidence_interval_low', sa.Integer(), nullable=True),
    sa.Column('confidence_interval_high', sa.Integer(), nullable=True),
    sa.Column('baseline_target_value', sa.Integer(), nullable=True),
    sa.Column('baseline_forecast_value', sa.Integer(), nullable=True),
    sa.Column('baseline_achievement_rate', sa.Float(), nullable=True),
    sa.Column('baseline_risk_level', sa.String(), nullable=True),
    sa.Column('baseline_confidence_interval_low', sa.Integer(), nullable=True),
    sa.Column('baseline_confidence_interval_high', sa.Integer(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=True),
    sa.Column('impact_analysis', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('territories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('hospital_count', sa.Integer(), nullable=True),
    sa.Column('rep_count', sa.Integer(), nullable=True),
    sa.Column('target_revenue', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('territory_performances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('territory_id', sa.String(), nullable=True),
    sa.Column('hospital_count', sa.Integer(), nullable=True),
    sa.Column('rep_count', sa.Integer(), nullable=True),
    sa.Column('target_revenue', sa.Integer(), nullable=True),
    sa.Column('actual_revenue', sa.Integer(), nullable=True),
    sa.Column('performance_rank', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_series_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('object_id', sa.String(), nullable=False),
    sa.Column('series_name', sa.String(), nullable=False),
    sa.Column('timestamp', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_series_data_object_id'), 'time_series_data', ['object_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('visit_feedbacks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('feedback_type', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('feedback_sentiment', sa.String(), nullable=True),
    sa.Column('key_insights', sa.Text(), nullable=True),
    sa.Column('follow_up_required', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visit_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('visit_type', sa.String(), nullable=True),
    sa.Column('visit_status', sa.String(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('actual_content', sa.Text(), nullable=True),
    sa.Column('key_insights', sa.Text(), nullable=True),
    sa.Column('compliance_score', sa.Integer(), nullable=True),
    sa.Column('effectiveness_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visit_records')
    op.drop_table('visit_feedbacks')
    op.drop_table('users')
    op.drop_index(op.f('ix_time_series_data_object_id'), table_name='time_series_data')
    op.drop_table('time_series_data')
    op.drop_table('territory_performances')
    op.drop_table('territories')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_scenario_parameters_scenario_id'), table_name='scenario_parameters')
    op.drop_table('scenario_parameters')
    op.drop_table('sales_targets')
    op.drop_table('sales_reps')
    op.drop_table('sales_flows')
    op.drop_table('rws_projects')
    op.drop_table('research_collaborations')
    op.drop_index(op.f('ix_reminders_user_id'), table_name='reminders')
    op.drop_table('reminders')
    op.drop_table('recovery_plans')
    op.drop_table('products')
    op.drop_table('product_flows')
    op.drop_table('pdca_plans')
    op.drop_table('patient_programs')
    op.drop_table('ontology_objects')
    op.drop_index(op.f('ix_object_links_source_id'), table_name='object_links')
    op.drop_table('object_links')
    op.drop_index(op.f('ix_object_events_object_id'), table_name='object_events')
    op.drop_table('object_events')
    op.drop_index(op.f('ix_object_actions_object_id'), table_name='object_actions')
    op.drop_table('object_actions')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('meeting_compliances')
    op.drop_table('market_potentials')
    op.drop_table('labor_payments')
    op.drop_table('inference_rules')
    op.drop_table('inference_results')
    op.drop_table('hospitals')
    op.drop_table('hospital_strategies')
    op.drop_table('hospital_developments')
    op.drop_table('expense_rois')
    op.drop_table('expense_compliances')
    op.drop_table('expense_classifications')
    op.drop_table('doctors')
    op.drop_table('department_researches')
    op.drop_table('customer_compliances')
    op.drop_table('customer_categories')
    op.drop_table('cost_drivers')
    op.drop_table('compliance_rules')
    op.drop_table('compliance_alerts')
    op.drop_table('clinical_trials')
    op.drop_index(op.f('ix_chat_threads_user_id'), table_name='chat_threads')
    op.drop_table('chat_threads')
    op.drop_index(op.f('ix_chat_messages_thread_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_table('budget_categories')
    op.drop_table('audit_log')
    op.drop_table('agent_status')
    op.drop_table('action_proposals')
    op.drop_index(op.f('ix_action_parameters_action_id'), table_name='action_parameters')
    op.drop_table('action_parameters')
    op.drop_table('academic_events')
    # ### end Alembic commands ###
